# Generated by Django 4.1 on 2022-10-23 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
        ('company', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_image', to='gallery.galleryitem'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='profile_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_image', to='gallery.galleryitem'),
        ),
    ]
