# Generated by Django 4.1 on 2022-08-30 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_rename_gallery_galleryitem'),
        ('company', '0003_accessibility_companyprofile_accessibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cover_image', to='gallery.galleryitem'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='profile_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_image', to='gallery.galleryitem'),
        ),
    ]
