# Generated by Django 4.1 on 2022-08-30 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessibility',
            options={'verbose_name_plural': 'accessibilities'},
        ),
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'activities'},
        ),
        migrations.AlterModelOptions(
            name='difficulty',
            options={'verbose_name_plural': 'difficulties'},
        ),
        migrations.AlterField(
            model_name='activityprofile',
            name='accessibility',
            field=models.ManyToManyField(blank=True, to='activity.accessibility'),
        ),
    ]
