# Generated by Django 4.1 on 2022-10-23 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
        ('activity', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityprofile',
            name='main_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_main_image', to='gallery.galleryitem'),
        ),
    ]
