# Generated by Django 4.1 on 2022-10-26 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_companyprofile_cover_image_and_more'),
        ('activity', '0003_alter_activityprofile_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityprofile',
            name='guideline',
            field=models.ManyToManyField(blank=True, limit_choices_to=1, to='company.guideline'),
        ),
    ]
