# Generated by Django 4.1 on 2022-10-13 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_remove_activityprofile_accessibility_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityprofile',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='activityprofile',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='activityprofile',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='activityprofile',
            name='image4',
        ),
    ]
