# Generated by Django 4.1 on 2022-10-15 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_remove_activityprofile_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityprofile',
            name='short_description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='activityprofile',
            name='website_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
