# Generated by Django 4.1 on 2022-11-01 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_activitytheme_activitytype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityprofile',
            name='activity_theme',
            field=models.ManyToManyField(blank=True, to='activity.activitytheme'),
        ),
        migrations.AddField(
            model_name='activityprofile',
            name='activity_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activity.activitytype'),
        ),
    ]
