# Generated by Django 4.1 on 2022-11-01 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_activityprofile_activity_theme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityprofile',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
