# Generated by Django 4.1 on 2022-11-13 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactform', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactform1',
            options={'verbose_name': 'Contact Form(1) submission', 'verbose_name_plural': 'Contact Form(1) submissions'},
        ),
    ]
