# Generated by Django 4.1 on 2022-08-30 07:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0002_alter_company_options'),
        ('activity', '0002_alter_accessibility_options_alter_activity_options_and_more'),
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gallery',
            new_name='GalleryItem',
        ),
    ]
